EXTRA_CPPFLAGS  ?=
ifeq ("$(CONFIG_CHIP_NAME)", "BL702")
EXTRA_CPPFLAGS  += -D BL_SDK_VER=\"release_bl_iot_sdk_1.6.40-1838-g97c99f8e5-dirty\"
EXTRA_CPPFLAGS  += -D BL_SDK_STDDRV_VER=\"55fe28a\"
EXTRA_CPPFLAGS  += -D BL_SDK_STDCOM_VER=\"9fe1995\"
EXTRA_CPPFLAGS  += -D BL_SDK_RF_VER=\"e203dee\"
endif
ifeq ("$(CONFIG_CHIP_NAME)", "BL702L")
EXTRA_CPPFLAGS  += -D BL_SDK_VER=\"release_bl_iot_sdk_1.6.40-1838-g97c99f8e5-dirty\"
EXTRA_CPPFLAGS  += -D BL_SDK_STDDRV_VER=\"54b9bcc\"
EXTRA_CPPFLAGS  += -D BL_SDK_STDCOM_VER=\"88edf7b\"
EXTRA_CPPFLAGS  += -D BL_SDK_RF_VER=\"v1.0.0\"
endif
