EXTRA_CPPFLAGS  ?=
ifeq ("$(CONFIG_CHIP_NAME)", "BL702")
EXTRA_CPPFLAGS  += -D BL_SDK_VER=\"release_bl_iot_sdk_1.6.40-1705-g429b6af2b\"
EXTRA_CPPFLAGS  += -D BL_SDK_STDDRV_VER=\"f52e35a\"
EXTRA_CPPFLAGS  += -D BL_SDK_STDCOM_VER=\"9fe1995\"
EXTRA_CPPFLAGS  += -D BL_SDK_RF_VER=\"e203dee\"
endif
ifeq ("$(CONFIG_CHIP_NAME)", "BL702L")
EXTRA_CPPFLAGS  += -D BL_SDK_VER=\"release_bl_iot_sdk_1.6.40-1705-g429b6af2b\"
EXTRA_CPPFLAGS  += -D BL_SDK_STDDRV_VER=\"cc99af0\"
EXTRA_CPPFLAGS  += -D BL_SDK_STDCOM_VER=\"88edf7b\"
EXTRA_CPPFLAGS  += -D BL_SDK_RF_VER=\"v1.0.0\"
endif
