#
#compiler flag config domain
#

#
#board config domain
#

#firmware config domain
#
CONFIG_CHIP_NAME := BL702L
CONFIG_BUILD_ROM_CODE := 1
CONFIG_BLE_EM_SIZE := 8K
#CONFIG_PDS_ENABLE := 1
CONFIG_DISABLE_PRINT := 0
CONFIG_DBG_RUN_ON_FPGA := 0
CONFIG_BL702_USE_ROM_DRIVER := 1

CONFIG_SYS_COMMON_MAIN_ENABLE := 1
CONFIG_SYS_APP_TASK_STACK_SIZE := 2048
CONFIG_SYS_APP_TASK_PRIORITY := 14
CONFIG_SYS_BLOG_ENABLE := 1

CONFIG_GPIO_SIM_PRINT := 1
CONFIG_GPIO_SIM_PRINT_TX_PIN := 8
CONFIG_GPIO_SIM_PRINT_BAUDRATE := 1000000

CONFIG_BL702_USE_LHAL := 1
CONF_ENABLE_COREDUMP:=1

