[ req ]
default_bits        = 4096
default_keyfile     = root_ca.key
distinguished_name  = subject
req_extensions      = req_ext
x509_extensions     = v3_ca

[ subject ]
countryName         = Country Name (2 letter code)
countryName_default = CN
stateOrProvinceName = State or Province Name (full name)
stateOrProvinceName_default = Beijing
localityName        = Locality Name (eg, city)
localityName_default = Beijing
organizationName    = Organization Name (eg, company)
organizationName_default = bfl
organizationalUnitName = Organizational Unit Name (eg, section)
organizationalUnitName_default = bfl
commonName          = Common Name (eg, your name or your server's hostname)
commonName_default  = 07af0000-1111-2222-3333-18b905de8aa3 BCID:0A38 BPID:0001

[ req_ext ]
subjectKeyIdentifier = hash
basicConstraints     = CA:TRUE
keyUsage             = keyCertSign, cRLSign

[ v3_ca ]
basicConstraints     = CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
certificatePolicies  = critical,ia5org,1.2.3.4
keyUsage             = keyAgreement


[ ia5org ]
policyIdentifier = 1.2.3.4
