#
#compiler flag config domain
#

#
#board config domain
#


#
#app specific config domain
#

CONFIG_CHIP_NAME := BL702

CONFIG_USE_STDLIB_MALLOC := 0

CONFIG_BUILD_ROM_CODE := 1

CONFIG_EASYFLASH_ENABLE:=1

# use internal RC32K by default; may set to 1 for better accuracy if there is XTAL32K on the board
CONFIG_USE_XTAL32K := 0

# disable temperature calibration by default
CONFIG_TCAL := 0

ifeq ($(CONFIG_PDS_ENABLE),1)
CONFIG_CLI_DISABLE := 1
CONFIG_BT_STACK_CLI := 0
CONFIG_PDS_LEVEL ?= 31
ifeq ($(CONFIG_PDS_LEVEL),31)
CONFIG_LINK_CUSTOMER := 1
endif

# use XTAL32K for ble pds31
CONFIG_USE_XTAL32K := 1
endif

CONFIG_BL702_USE_ROM_DRIVER := 1

LOG_ENABLED_COMPONENTS := hosal vfs

CONF_ENABLE_COREDUMP:=1

CONFIG_SYS_COMMON_MAIN_ENABLE := 1
CONFIG_SYS_APP_TASK_STACK_SIZE := 2048
CONFIG_SYS_APP_TASK_PRIORITY := 15
CONFIG_SYS_BLOG_ENABLE := 1

ifneq ($(CONFIG_CLI_DISABLE),1)
CONFIG_SYS_VFS_ENABLE := 1
CONFIG_SYS_VFS_UART_ENABLE := 1
CONFIG_SYS_AOS_CLI_ENABLE := 1
CONFIG_SYS_AOS_LOOP_ENABLE := 1
endif